name: 01 - Building-Blocks

on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"
  echo-goodby:
    runs-on: ubuntu-latest
    steps:
      - name: Succesful step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"

